
set(FLINTOS_SRCS
    "../../../flintjvm/vm/src/flint.cpp"
    "../../../flintjvm/vm/src/flint_utf8.cpp"
    "../../../flintjvm/vm/src/flint_hook.cpp"
    "../../../flintjvm/vm/src/flint_mutex.cpp"
    "../../../flintjvm/vm/src/flint_common.cpp"
    "../../../flintjvm/vm/src/flint_const_pool.cpp"
    "../../../flintjvm/vm/src/flint_fields_data.cpp"
    "../../../flintjvm/vm/src/flint_field_info.cpp"
    "../../../flintjvm/vm/src/flint_method_info.cpp"
    "../../../flintjvm/vm/src/flint_java_class.cpp"
    "../../../flintjvm/vm/src/flint_java_object.cpp"
    "../../../flintjvm/vm/src/flint_java_string.cpp"
    "../../../flintjvm/vm/src/flint_java_thread.cpp"
    "../../../flintjvm/vm/src/flint_java_throwable.cpp"
    "../../../flintjvm/vm/src/flint_array_object.cpp"
    "../../../flintjvm/vm/src/flint_class_loader.cpp"
    "../../../flintjvm/vm/src/flint_execution.cpp"
    "../../../flintjvm/vm/src/flint_debugger.cpp"
    "../../../flintjvm/vm/src/flint_utf8_dict_node.cpp"
    "../../../flintjvm/vm/src/flint_file_reader.cpp"
    "../../../flintjvm/vm/src/flint_zip_file_reader.cpp"
    "../../../flintjvm/vm/src/flint_java_class_dict_node.cpp"
    "../../../flintjvm/vm/src/flint_java_string_dict_node.cpp"
    "../../../flintjvm/vm/src/flint_native_interface.cpp"

    "../../../flintjvm/impl/src/lwip_system_net_api.cpp"

    "../../../flintjvm/native/common/src/flint_native.cpp"
    "../../../flintjvm/native/common/src/flint_native_common.cpp"

    "../../../flintjvm/native/base/src/flint_native_math.cpp"
    "../../../flintjvm/native/base/src/flint_native_class.cpp"
    "../../../flintjvm/native/base/src/flint_native_array.cpp"
    "../../../flintjvm/native/base/src/flint_native_float.cpp"
    "../../../flintjvm/native/base/src/flint_native_double.cpp"
    "../../../flintjvm/native/base/src/flint_native_object.cpp"
    "../../../flintjvm/native/base/src/flint_native_string.cpp"
    "../../../flintjvm/native/base/src/flint_native_system.cpp"
    "../../../flintjvm/native/base/src/flint_native_thread.cpp"
    "../../../flintjvm/native/base/src/flint_native_method.cpp"
    "../../../flintjvm/native/base/src/flint_native_character.cpp"
    "../../../flintjvm/native/base/src/flint_native_reflection.cpp"
    "../../../flintjvm/native/base/src/flint_native_constructor.cpp"
    "../../../flintjvm/native/base/src/flint_native_crc32.cpp"
    "../../../flintjvm/native/base/src/flint_native_file.cpp"
    "../../../flintjvm/native/base/src/flint_native_file_descriptor.cpp"
    "../../../flintjvm/native/base/src/flint_native_file_input_stream.cpp"
    "../../../flintjvm/native/base/src/flint_native_file_output_stream.cpp"
    "../../../flintjvm/native/base/src/flint_native_random_access_file.cpp"
    "../../../flintjvm/native/base/src/flint_native_crc32.cpp"

    "../../../flintjvm/native/net/src/flint_native_flint_socket_impl.cpp"
    "../../../flintjvm/native/net/src/flint_native_flint_inet_address_impl.cpp"
    "../../../flintjvm/native/net/src/flint_native_flint_socket_input_stream.cpp"
    "../../../flintjvm/native/net/src/flint_native_flint_socket_output_stream.cpp"
    "../../../flintjvm/native/net/src/flint_native_flint_datagram_socket_impl.cpp"

    "../../../flintjvm/native/draw/src/flint_fixed_point.cpp"
    "../../../flintjvm/native/draw/src/flint_gfx_common.cpp"
    "../../../flintjvm/native/draw/src/flint_rgb565_sw_gfx.cpp"
    "../../../flintjvm/native/draw/src/flint_rgb565_sw_gfx_helper.cpp"
    "../../../flintjvm/native/draw/src/flint_native_graphics.cpp"
    "../../../flintjvm/native/draw/src/flint_native_rgb565_graphics.cpp"

    "../../../flintos/core/src/flintos.cpp"
    "../../../flintos/core/src/flint_system_api.cpp"
    "../../../flintos/core/src/flintos_debugger.cpp"
    "../../../flintos/core/src/flintos_audio_service.cpp"
    "../../../flintos/core/src/flintos_display_service.cpp"

    "../../../flintos/native/src/flintos_native.cpp"
    "../../../flintos/native/src/flintos_native_wifi.cpp"
    "../../../flintos/native/src/flintos_native_audio.cpp"
    "../../../flintos/native/src/flintos_native_display.cpp"
    "../../../flintos/native/src/flintos_native_midp.cpp"
    "../../../flintos/native/src/flintos_native_midp_png.cpp"
)

set(FLINTJVM_INCS
    INCLUDE_DIRS "../../../flintjvm/vm/inc"
    INCLUDE_DIRS "../../../flintjvm/impl/inc"

    INCLUDE_DIRS "../../../flintjvm/native/net/inc"
    INCLUDE_DIRS "../../../flintjvm/native/base/inc"
    INCLUDE_DIRS "../../../flintjvm/native/common/inc"
    INCLUDE_DIRS "../../../flintjvm/native/draw/inc"

    INCLUDE_DIRS "../../../flintos/core/inc"
    INCLUDE_DIRS "../../../flintos/native/inc"
)
